### ISSUE TITLE
October Technical Updates (due Oct 30)

### ISSUE THREAD

**Issue by MichalaH** [sofwerx/cdb2-concept#41]
Participant Name/Company:
Breakout Group:
Work Completed: list prototyping, development, TIEs, meetings, any and all work for this effort for the month
Work Planned: list work that is planned for the following month
Risks/Issues/Blockers: list any risks to accomplishing the work, anything that is blocking, or any issues

Paid participants, please use the above template to submit monthly technical work reports in a comment below. I will give this info to SOCOM/SOFWERX as the monthly update. The people we are expecting to see give updates are listed below.

Please send me a Slack or email (mhill@cognitics.net) verifying your meeting attendance this month so I can make sure my notes are correct. If you had someone attend meetings on your behalf, please list that person's name and when they attended.
• Hermann Brassard
• Ryan Franz
• Jay Freeman
• David Graham
• Greg Peele
• Carl Reed
• Jerome St-Louis
• Sean Lilley
Thank you!

**Comment by PresagisHermann** [comment]
**Participant Name/Company:** 	Hermann Brassard and Anthony Mirabeau / Presagis
**Breakout Group:** 		3D models
**Meeting attendance:**		5 meetings (1,8,15,22,29 Oct)
**Work Completed:** 
Completed CDB conversion from OpenFlight to glTF 3D models with index file
Writing large portion of the 3D model report section, reviewing baseline content from Carl, adding much of the content and addressing feedback notes. Provided early contributions and multiple iterations to facilitate review and feedback. Provided contribution in asciidoc on GitHub. 
**Work Planned:** 
None aside addressing comments on report

**Risks/Issues/Blockers:** 
None

**Comment by UnclePoole** [comment]
Participant Name/Company: Greg Peele / Geometric Progress LLC
Breakout Group: Attribution
Work Completed:
- Attended all weekly sprint meetings
- Conducted assessment of detailed mapping between TDS/GGDM/CDB and discussed with Michala Hill and Holly Black with a primary focus on mapping strategy for CDB Feature Subcode
- Reviewed current OGC CDB ticket regarding NAS compliance and associated ISO 19109 standard
- Wrote Engineering Report section on attribution summarizing data model background, experiment design and goals, detailed findings, and summary of recommendations to align CDB with NAS/GGDM augmented with DGIM and other sources
- Presented cross-project briefing regarding aligning with NAS (OWT-centric but with CDB X tie-in) to USGIF MS&G WG and to NGA 
- Submitted final report

Work Planned: Address Engineering Report review comments as appropriate
Risks/Issues/Blockers: nope

**Comment by jerstlouis** [comment]
**Participant Name/Company:** Jerome St-Louis / Ecere
**Breakout Group:** 		Tiling
**Meeting attendance:**		All meetings; was quite late for one which also ended earlier but provided an update
**Work Completed:** 
- Discovered and fixed a number of issues in our CDB importing process
- Fixed loss of vertical resolution in Elevation GeoPackage(s) generation; making use of per-tile scales and offsets for PNG
- Started a draft extension for storing 3D models and textures inside GeoPackages
- Completed experiments tiling points referencing 3D models in table (Mapbox Vector Tiles & glTF or GNOSIS Map Tiles & E3D)
- Completed experiments tiling 3D models batched as glTF or E3D in tiles table `tile_data`, assuming ENU/tile center origin 
- Completed experiments tiling vector data (as Mapbox Vector Tiles and GNOSIS Map Tiles)
- Completed experiments with multiple LoD grouping settings, adjusting to latest agreed directory/file naming conventions
- Completed experiments with single file GeoPackages
- Completed experiments with single vs. separate packages for data layers encoding the entire San Diego CDB X dataset
- Summarized latest experiments on Wiki in Ecere Tiling Experiment 3
- Reviewed and contributed to Tiling section of Engineering Report

**Work Planned:** 
- Complete ER contributions by Saturday, October 31st.

**Risks/Issues/Blockers:** 
None

**Comment by ryanfranz** [comment]
**Participant Name/Company**:  Ryan Franz, FSI
**Breakout Group**:  Tiling and Coverages
**Meetings**:  Attended all weekly sprint meetings
**Work Completed**: Edited the chapter on coverages, and added additional descriptions and details, across two different pull requests
**Work Planned**: Upload our experiment data to the OGC website and update the links in the ER by Oct 31
**Risks/Issues/Blockers**: None

**Comment by DavidFLOR** [comment]
**Participant Name/Company:** David Graham, Eagle Cap Systems
**Breakout Group:** Top Level Integration / Metadata; ER Editors
**Meetings:** Attended 4/5 weekly meetings; missed one meeting for family emergency; notified moderator in advance and received a back brief after
**Work Completed:** 
- Reviewed WIP by other sub-groups for insight/opportunities for system integration and/or metadata impacts
- Continued work on draft ER sub-.adoc on Top Level Metadata / Integration
- Reviewed ER submission on attribution; merged; moved content appropriately for summary recommendations
- Reviewed existing ER front matter; resolved question of whether SOFWERX copyright / other front-matter needed to be used to replace OGC boilerplate in the current draft template

**Work Planned:** 
- Continued collaboration and support with Carl Reed in what I think will be a pretty intensive ER editing effort for the next seven days
- Begin work on PPT and other artifacts to socialize and explain the Sprint effort to the SWG
 
**Risks/Issues/Blockers:**  I have an ongoing personal/family situation, of which the moderator is aware, that can unexpectedly take precedent over my time for significant blocks of time.

**Comment by freemanjay** [comment]
Participant Name/Company: Mike Lokuta, Jay Freeman, Holly Black, Erik Henning -- CAE USA
Breakout Group: Multiple (metadata, vectors in geopakage, attribution)
Meetings: Attended weekly sprint meetings
Work Completed: Document metadata information from NGA and GeoPackage experiments
Work Planned: Upload documentation to the engineering report
Risks/Issues/Blockers: None

**Comment by lilleyse** [comment]
**Participant Name/Company:** Sean Lilley – Cesium
**Breakout Group:** 3D models
**Meetings:** Attended all weekly meetings
**Work completed:** Contributed to the 3D Models engineering report - described the CDB glTF extension in more detail and proposed a future roadmap.
**Work Planned:** None
**Risk/Issues/Blocker:** None

**Comment by MichalaH** [comment]
Project complete, closing admin items.
