### ISSUE TITLE
Participant Final Reports (due Oct 31)

### ISSUE THREAD

**Issue by MichalaH** [sofwerx/cdb2-concept#42]
Please email Susan and Crystal the final reports by October 31.

The report should include a summary of activities to date, team contributions, and recommendations to OGC and other standards bodies.

Specific details to include:
Name of breakout group(s) in which you were involved
Summary of breakout group participation
Summary of experimentation
Description of prototypes and data outputs

Add any additional information on your activities as needed.

Thank you all for a great sprint effort!

**Comment by cnreediii** [comment]
Participant Name/Company: Carl Reed (Carl Reed &Associates)

Breakout Group: Coverages/Tiles and ER Editor

Work Completed: list prototyping, development, TIEs, meetings, any and all work for this effort for the month: Attended all group conference calls, collaborated with the Coverages/Tiles subgroup, participated in Slack and Git Issues discussions, and continued work on the draft CDB X ER. The latter included more work on the boilerplate content, began review of the Attribute section, initial compiling of content for Exec Summary, and other tasks targeted at completing the ER by November 7.

Work Planned: list work that is planned for the following month: Continue work away on the ER, collaborate with David G on edits as well as the Exec summary. Completion target date of November 7.

Risks/Issues/Blockers: list any risks to accomplishing the work, anything that is blocking, or any issues: Some Sub-groups have not posted draft content to work with!

Thanks Michala! And thanks Sofwerx and SOCOM!

**Comment by MichalaH** [comment]
Project complete, closing admin items.
